import { PrinterDefinition, PrintJob, AuditLogEntry, UserProfile } from '../types';

export const INITIAL_PRINTERS: PrinterDefinition[] = [
  {
    id: 'prn-os-2',
    name: 'Microsoft Print to PDF',
    model: 'Microsoft Print To PDF',
    brand: 'Desktop PDF',
    dpi: 300,
    ipAddress: 'PORTPROMPT:',
    port: 9100,
    status: 'online',
    protocol: 'pdf',
    location: 'Local Workstation / USB Spooler',
    mediaWidth: 210,
    mediaHeight: 297,
  },
  {
    id: 'prn-os-3',
    name: 'Export to WPS PDF',
    model: 'Kingsoft Virtual Printer Driver',
    brand: 'Desktop PDF',
    dpi: 300,
    ipAddress: 'Kingsoft Virtual Printer Port',
    port: 9100,
    status: 'online',
    protocol: 'pdf',
    location: 'Local Workstation / USB Spooler',
    mediaWidth: 210,
    mediaHeight: 297,
  },
  {
    id: 'prn-os-1',
    name: 'OneNote (Desktop)',
    model: 'Send to Microsoft OneNote 16 Driver',
    brand: 'Desktop PDF',
    dpi: 300,
    ipAddress: 'nul:',
    port: 9100,
    status: 'online',
    protocol: 'pdf',
    location: 'Local Workstation / USB Spooler',
    mediaWidth: 210,
    mediaHeight: 297,
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-super-admin',
    name: 'Super Administrator',
    email: 'superadmin@gmail.com',
    password: 'superadmin@gmail.com',
    role: 'Super Admin',
    department: 'Enterprise Security & Governance',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces',
    status: 'approved',
    isApproved: true,
    createdAt: '2026-08-01T00:00:00Z',
    permissions: {
      canDesignTemplates: true,
      canCreateTemplates: true,
      canDeleteTemplates: true,
      canApproveWorkflow: true,
      canPrintAndSpool: true,
      canManageDatasets: true,
      canCalibratePrinters: true,
      canManageLicense: true,
      canDownloadDesktopApp: true,
      canViewAuditLogs: true,
    },
  },
  {
    id: 'usr-admin-01',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@company.com',
    password: 'password123',
    role: 'Admin',
    department: 'Packaging Engineering',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=faces',
    status: 'approved',
    isApproved: true,
    createdAt: '2026-08-10T10:00:00Z',
    approvedAt: '2026-08-10T11:00:00Z',
    approvedBy: 'Super Administrator',
    permissions: {
      canDesignTemplates: true,
      canCreateTemplates: true,
      canDeleteTemplates: false,
      canApproveWorkflow: true,
      canPrintAndSpool: true,
      canManageDatasets: true,
      canCalibratePrinters: true,
      canManageLicense: false,
      canDownloadDesktopApp: true,
      canViewAuditLogs: true,
    },
  },
  {
    id: 'usr-admin-pending',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@pharma.com',
    password: 'password123',
    role: 'Admin',
    department: 'Cleanroom Serialization Operations',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=faces',
    status: 'pending_approval',
    isApproved: false,
    createdAt: '2026-08-21T14:30:00Z',
    permissions: {
      canDesignTemplates: true,
      canCreateTemplates: true,
      canDeleteTemplates: false,
      canApproveWorkflow: true,
      canPrintAndSpool: true,
      canManageDatasets: true,
      canCalibratePrinters: false,
      canManageLicense: false,
      canDownloadDesktopApp: true,
      canViewAuditLogs: true,
    },
  },
  {
    id: 'usr-designer',
    name: 'Shivam',
    email: 'shivam@gmail.com',
    password: 'password123',
    role: 'Admin',
    department: 'Label Management & Engineering',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces',
    status: 'approved',
    isApproved: true,
    createdAt: '2026-08-15T08:00:00Z',
    permissions: {
      canDesignTemplates: true,
      canCreateTemplates: true,
      canDeleteTemplates: true,
      canApproveWorkflow: true,
      canPrintAndSpool: true,
      canManageDatasets: true,
      canCalibratePrinters: true,
      canManageLicense: true,
      canDownloadDesktopApp: true,
      canViewAuditLogs: true,
    },
  }
];

export const INITIAL_BATCH_JOBS: any[] = [
  {
    id: 'BAT-2026-001',
    jobCode: 'BAT-2026-001',
    templateId: 'tmpl-fda-udi-pharma-80x50',
    templateName: 'FDA UDI Medical Device Serialization Label (80x50 mm)',
    productName: 'SURGICAL GUIDE PIN 3.2MM',
    itemCode: 'ITM-MED-88910',
    batchNumber: 'BATCH-2026-X8',
    lotNumber: 'LOT-9921',
    mfgDate: '2026-08-01',
    expDate: '2029-08-01',
    mrp: '$149.00',
    packFrom: 1,
    packTo: 10,
    totalPages: 10,
    status: 'sent_to_viewer',
    generatedBy: 'Adam Admin',
    generatedAt: '2026-08-16 10:20:00',
    sentToViewerAt: '2026-08-16 10:22:00',
    items: Array.from({ length: 10 }, (_, i) => ({
      pageNumber: i + 1,
      packNumber: i + 1,
      packLabel: `Pack ${i + 1}`,
      itemCode: 'ITM-MED-88910',
      batchNumber: 'BATCH-2026-X8',
      lotNumber: 'LOT-9921',
      mfgDate: '2026-08-01',
      expDate: '2029-08-01',
      mrp: '$149.00',
      serialNumber: `SN-884920${i + 1}`,
      fullBarcodeData: `(01)00850006539987(17)290801(10)LOT-9921(21)884920${i + 1}`,
      isPrinted: false,
    }))
  },
  {
    id: 'BAT-2026-002',
    jobCode: 'BAT-2026-002',
    templateId: 'tmpl-gs1-logistics-102x152',
    templateName: 'GS1-128 Logistics Shipping Pallet Label (4x6 in)',
    productName: 'Industrial Fastener Assortment Box',
    itemCode: 'ITM-LOG-7440',
    batchNumber: 'BN-9021',
    lotNumber: 'LOT-2026-B9',
    mfgDate: '2026-08-10',
    expDate: '2027-12-31',
    mrp: '$520.00',
    packFrom: 1,
    packTo: 5,
    totalPages: 5,
    status: 'sent_to_viewer',
    generatedBy: 'Adam Admin',
    generatedAt: '2026-08-17 14:15:00',
    sentToViewerAt: '2026-08-17 14:16:00',
    items: Array.from({ length: 5 }, (_, i) => ({
      pageNumber: i + 1,
      packNumber: i + 1,
      packLabel: `Pack ${i + 1}`,
      itemCode: 'ITM-LOG-7440',
      batchNumber: 'BN-9021',
      lotNumber: 'LOT-2026-B9',
      mfgDate: '2026-08-10',
      expDate: '2027-12-31',
      mrp: '$520.00',
      serialNumber: `SSCC-00850006512345678${i + 1}`,
      fullBarcodeData: `(00)008500065123456784(10)LOT-2026-B9`,
      isPrinted: false,
    }))
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud-101',
    timestamp: '2026-08-14T17:45:00Z',
    user: 'Marcus Vance (Quality Reviewer)',
    userRole: 'Quality Reviewer',
    action: 'APPROVE_TEMPLATE',
    details: 'Approved FDA UDI Medical Device Serialization Label (v2.1) following ISO 13485 verification check.',
    entityId: 'tmpl-fda-udi-pharma-80x50',
    entityName: 'FDA UDI Medical Device Serialization Label',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'aud-102',
    timestamp: '2026-08-14T17:15:20Z',
    user: 'David Chen (Print Operator)',
    userRole: 'Print Operator',
    action: 'PRINT_JOB_DISPATCH',
    details: 'Dispatched batch print job #PJ-9021 (500 copies) to Zebra ZT410 Industrial Line 1.',
    entityId: 'pj-9021',
    entityName: 'Batch Shipping Manifest Labels',
    ipAddress: '192.168.1.72',
  },
  {
    id: 'aud-103',
    timestamp: '2026-08-14T16:30:10Z',
    user: 'Elena Rostova (Label Designer)',
    userRole: 'Label Designer',
    action: 'CREATE_TEMPLATE',
    details: 'Created new Chemical GHS Hazmat Classification Template with dual-language GHS statements.',
    entityId: 'tmpl-chemical-ghs-105x74',
    entityName: 'Chemical GHS Hazmat Classification',
    ipAddress: '192.168.1.33',
  },
  {
    id: 'aud-104',
    timestamp: '2026-08-14T15:10:00Z',
    user: 'Sarah Jenkins (Admin)',
    userRole: 'Admin',
    action: 'SYSTEM_CONFIG',
    details: 'Updated thermal print server timeout thresholds and configured 600 DPI SATO printer endpoints.',
    ipAddress: '192.168.1.10',
  }
];

export const INITIAL_PRINT_JOBS: PrintJob[] = [
  {
    id: 'PJ-9021',
    templateId: 'tmpl-gs1-logistics-102x152',
    templateName: 'GS1-128 Logistics Shipping Pallet Label (4x6 in)',
    printerId: 'prn-zebra-zt410',
    printerName: 'Zebra ZT410 Industrial (Line 1)',
    copies: 250,
    recordCount: 50,
    status: 'completed',
    format: 'zpl',
    submittedBy: 'David Chen',
    submittedAt: '2026-08-14T16:00:00Z',
    completedAt: '2026-08-14T16:04:12Z',
    progressPercent: 100,
  },
  {
    id: 'PJ-9022',
    templateId: 'tmpl-fda-udi-pharma-80x50',
    templateName: 'FDA UDI Medical Device Serialization Label',
    printerId: 'prn-zebra-zd620',
    printerName: 'Zebra ZD620 Desktop (Pharma Cleanroom)',
    copies: 50,
    recordCount: 50,
    status: 'printing',
    format: 'zpl',
    submittedBy: 'Marcus Vance',
    submittedAt: '2026-08-14T18:10:00Z',
    progressPercent: 68,
  },
  {
    id: 'PJ-9023',
    templateId: 'tmpl-retail-price-tag-50x30',
    templateName: 'Retail Product Price & EAN-13 Tag',
    printerId: 'prn-virtual-pdf',
    printerName: 'Virtual PDF Vector Spooler',
    copies: 120,
    recordCount: 12,
    status: 'queued',
    format: 'pdf',
    submittedBy: 'Elena Rostova',
    submittedAt: '2026-08-14T18:15:00Z',
    progressPercent: 0,
  }
];
